### PR TITLE
Update com.google.firebase:firebase-config version to 19.2.0 to be compatible with latest version of @capacitor/push-notification plugin 

### PR DESCRIPTION
**Pull request by rgarciadelongoria**
This PR solve the dependency version conflict between this plugin and @capacitor/push-notification plugin latest version.

Captura de Pantalla 2022-08-18 a las 9 37 27

Captura de Pantalla 2022-08-18 a las 9 30 10

I need to update @capacitor/push-notification to 4.0.1 versión (Capacitor 4) because Android 12 (>=API 31) need new parameter to specify mutable or immutable flag.

### CODE REVIEW

**Comment by felipeclopes** [comment]
@gugahoi any chance you can merge this? I'm having the same incompatibility issue.

**Comment by felipeclopes** [comment]
@rgarciadelongoria, how did you get that dependency tree built?

**Comment by rgarciadelongoria** [comment]
> @rgarciadelongoria, how did you get that dependency tree built?

This is a android gradle dependency tree.

On terminal go to android folder and use this command:

`./gradlew app:dependencies`

**Comment by gugahoi** [comment]
I'll close this in favor of #17 since the changes here will break the release due to the name changes.

**Pull request closed without merging**
